[package]
name = "turbin3-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "1.18.26"
bs58 = "0.5.1"
solana-client = "1.18.26"
solana-program = "1.18.26"
borsh = "0.10.3"
solana-idlgen = { git = "https://github.com/deanmlittle/solana-idlgen.git" }